# -*- coding: utf-8 -*-
"""Covid_Analysis_Task-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yimfEKdc0Oqm7Ik1aiN-qYGSOa7fKDe6
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/Covid.csv')

# Display shape and top records
print("Shape of Dataset:", df.shape)
df.head()

import numpy as np

# Drop irrelevant column
df = df.drop(['Country/Region'], axis=1)

# Convert categorical to numeric
df = pd.get_dummies(df, drop_first=True)

# Replace missing values
df = df.fillna(0)

# Replace inf/-inf with NaN and then fill
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df = df.fillna(0)

# Check if anything suspicious remains
print(np.any(np.isnan(df)))        # Should be False
print(np.any(np.isinf(df)))        # Should be False

# Split features and label
X = df.drop('Deaths', axis=1)
y = df['Deaths']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("R² Score:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("MAE:", mean_absolute_error(y_test, y_pred))